### ISSUE TITLE
Enabling USB Mass Storage

### ISSUE THREAD

**Issue by febin92** [YaroST12/RAPHAEL_Kernel#2]
I noticed that the kernel was built without USB mass storage (CONFIG_USB_F_MASS_STORAGE) enabled, would there be any issues if I rebuild the kernel with it enabled for my use?

**Comment by YaroST12** [comment]
How did I not see this lol, I assume you mean CONFIG_USB_CONFIGFS_MASS_STORAGE because CONFIG_USB_F_MASS_STORAGE doesn't exist.

**Comment by febin92** [comment]
Yes

**Comment by YaroST12** [comment]
Added, will be in next release.
